project:
  type: website
  output-dir: _site

website:
  title: "ISA 401 Notes"
  favicon: favicon.png
  search: false
  navbar:
    right:
      - text: "Slides and schedule"
        href: https://github.com/fmegahed/isa401#schedule

format:
  html:
    theme: [cosmo, site.scss]
    toc: true
    toc-depth: 3
    code-copy: true
